### PR TITLE
Relax version constraint of mini_portile2

### PR DESCRIPTION
**Pull request by eagletmt**
I've tested with mini_portile2 v2.3.0.
I think there's no reason to specify upper-bound.

### CODE REVIEW

**Comment by eagletmt** [comment]
@yugui could you take a look?

**Comment by yugui** [comment]
LGTM. Thank you for your contribution!

**Comment by eagletmt** [comment]
Thank you for merging. Could you publish a new version to rubygems.org?
I'd like to use jsonnet gem with other gems which require more recent mini_portile2 gem (e.g. nokogiri https://rubygems.org/gems/nokogiri/versions/1.8.2 )

**Comment by yugui** [comment]
Ah, that's a reasonable. done.
https://rubygems.org/gems/jsonnet/versions/0.2.1

**Pull request merged**
